# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: db/development
  pool: 5
  username: postgres
  password: id080340

production:
  adapter: postgresql
  encoding: unicode
  database: db/production
  pool: 5
  username: postgres
  password: id080340


# production:
#   adapter: mysql2
#   encoding: utf8
#   database: <%= ENV['RDS_DB_NAME'] %>
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: <%= ENV['RDS_HOSTNAME'] %>
#   port: <%= ENV['RDS_PORT'] %>
# #  pool: 5
#  # timeout: 5000
