# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c256f35fead132c4c7dbe145a55583cf137924f10f1d08506bafaa9646af20a652b5b08dfdd027236068ef15a060ececfa65c125e4868807365677b1c2bce36d

test:
  secret_key_base: 78aa86f83e7e637c365ac768cb09e17f7cba08ca41ffb16a29fc471011c1e909cceee7c20c5720e485738d4c92dd9fe201401c72c220478d1a961eacc12ae26d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
